### ISSUE TITLE
Docs: Unclear data shapes

### ISSUE THREAD

**Issue by donpinkus** [jask-oss/reaviz#101]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Currently the docs don't show any of the data shapes except in the very first example. 

All the examples I've opened just have `data={someData}`. For maps, it's `data={worldData}`. I don't know or have a way to tell what those objects look like. This makes it really hard to use the library since we're guessing at the data shape. 

If the same data shape is used everywhere, can you call that out in the intro or somewhere? If different data shapes are used, can you inline that in the relevant places?

**Comment by amcdnl** [comment]
Yup - Thats on my list still. It does have a unified data shape. I'll try to get this added today! :)

**Comment by amcdnl** [comment]
Just added a few nootes - will expand it later tho - https://github.com/jask-oss/reaviz/commit/b8686152b4701806278e866b7a3b3a92aef3c002#diff-fbd76a3443d8cb15e78f5e02d7dadb1e
