### ISSUE TITLE
Gridline: missing property strokeDasharray

### ISSUE THREAD

**Issue by iwan-uschka** [jask-oss/reaviz#103]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[/] Bug report  
[ ] Performance issue
[\] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Grid line style property `stroke-dasharray` is set in `Gridline.module.scss` and can't be configured in `<Gridline>` props unlike other other values like `strokeWidth` and `strokeColor`.

## Expected behavior

Having a `strokeDasharray` property next to `strokeWidth` and `strokeColor` for `<Gridline>` would be cool.

**Comment by amcdnl** [comment]
Great idea - pushed and available via dev npm install.
