### ISSUE TITLE
Docs: Custom tool-tip implementation

### ISSUE THREAD

**Issue by South-Paw** [jask-oss/reaviz#111]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

There isn't any documentation of how to create your own custom tool-tips nor is there any documentation of the internal tool-tip component.

## Expected behavior

A page in the storybook to describe custom tooltip implementation with custom labels

## Minimal reproduction of the problem with instructions

n/a?

## What is the motivation / use case for changing the behavior?

We have graphs in our app that are based on hourly data points and I've set the `xAxis={<LinearXAxis type="time" />}` however the tool tips still show their labels as `dd/mm/yyyy` rather than `hh:mm:ss` (for example) and there is no way I can see to customize the tool tips.

## Environment

<pre><code>
Libs:
- react version: 16.12.0
- reaviz version: 7.2.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.16.3  
- Platform:  Windows  

Others:
- n/a

</code></pre>

**Comment by amcdnl** [comment]
Did some basic stuff - will add more later.

**Comment by alexiastandish** [comment]
Is there any new updates on this? It would be nice if the tooltip template could receive children so that the tooltips can actually be customizable while still receiving the data for x/y values.
