### ISSUE TITLE
PieChart not displaying the entire data

### ISSUE THREAD

**Issue by ynahmany** [jask-oss/reaviz#112]
Hi, 
 Again, great product!
We encounter with a strange issue. the data looks like: 
`0: {key: 0, data: 3}
1: {key: 1, data: 154}
2: {key: 2, data: 132}
3: {key: 3, data: 624}`

The smallest data - key:0, data: 3, cannot be seen.
![image](https://user-images.githubusercontent.com/7278548/69829041-1e52f880-1227-11ea-80f5-60e20db86f51.png)

The component is pretty straight forward: 
`<PieChart
      width={550}
      height={500}
      data={data}
      series={
        <PieArcSeries
          explode={true}
          colorScheme={chroma.scale(['#4dd0e1', '#1976d2']).colors(data.length)}
        />
      }
    />`

Thanks in advance!

**Comment by amcdnl** [comment]
Thanks! Gotcha - ya part of a pie chart is those cases but the PR seems to solve the issue :)
