### ISSUE TITLE
More detailed example how to mix data

### ISSUE THREAD

**Issue by wiesson** [jask-oss/reaviz#12]
## I'm submitting a...

<pre><code>
[x] Documentation issue or request
</code></pre>

## What is the motivation / use case for changing the behavior?

It would be great to see a more detailed example how to mix e.g. ScatterPlot with Line/Area data. In my current use case, I have time series data and I'd like to mix it with a Scatterplot to add certain meta-data to specific points. Are there maybe other options I have missed?

**Comment by amcdnl** [comment]
You would need to create a custom chart using the scatter and line series.

If you can send me an example of your data, maybe I can help make a demo for you.

**Comment by wiesson** [comment]
I checked the docs (https://github.com/jask-oss/reaviz/blob/master/docs/advanced/custom-charts.md) but I don't know where to start. 

Also it's quite hard for me to find out what this library can actually do. E.g. recharts offers a documentation, http://recharts.org/en-US/api while for reaviz I'm reading the source code, typings and stories.

What I'd like to do:
* How get started with a composable chart? (Same xAxis, same yAxis, but scatter combined with Area/Line)
* Can I render "disconnected" Lines/Areas if the value is `null`?

**Comment by amcdnl** [comment]
@wiesson - Ya, we are brand new -> docs and better examples come over time :). If you show me what your trying to do I can help for sure!

**Comment by veddermatic** [comment]
Not sure if this is it's own issue or not, but is it possible to have multiple unit types / axis? So for example, I have a set of 10 days, and for each day I have a temperature and the number of cups of coffee I drank. Is it possible to have dates on the X axis, then temperature on the left Y, and cups of coffee on the right Y?

**Comment by wiesson** [comment]
@amcdnl, here is a quick example - https://codesandbox.io/s/vqj442ol97 

I basically like to have notifications and sensor data in the same chart :) - Can I also adjust the yAxis? For our door sensors, we only have Open or Closed not [1, 0.5, 0].
