### ISSUE TITLE
Year Calendar w/ March Start does not start from March

### ISSUE THREAD

**Issue by lezan** [jask-oss/reaviz#122]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Year Calendar w/ March Start does not start from March, but from January, as the default one.

## Expected behavior
It need to start from March as excepted from title.

## Minimal reproduction of the problem with instructions
You can just check demo page because issue is present also there.
https://reaviz.io/?path=/docs/charts-heatmap-calendar--year-calendar-w-march-start

![Uploading Screenshot_2020-02-06 Charts Heatmap Calendar - Year Calendar w March Start ⋅ Storybook.png…]()

## Environment

<pre><code>
Libs:
- react version: 16.12.0
- reaviz version: 8.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 72.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 13.7.0 
- Platform:  Windows

</code></pre>

**Comment by steppy452** [comment]
I'm honestly not too sure what's going on with the docs tab on storybook, but if you go to the actual story, it is working correctly-ish (our data is actually offset to April and not March - PR to fix #126) but the component is working as expected:
https://reaviz.io/?path=/story/charts-heatmap-calendar--year-calendar-w-march-start
