### ISSUE TITLE
The tooltip color is not getting updated.

### ISSUE THREAD

**Issue by LeelaBasavaiah** [jask-oss/reaviz#123]
I am trying to change the color of my tooltip to black. By default its white and I have a white background. So its not visible. There is no sample code anywhere as to how to change the default color. Is this the correct way? <TooltipTemplate
                                                                              color='black'
                                                                              value={{
                                                                                x: data.x,
                                                                                y: data.y
                                                                              }}
                                                                            />
Full code is here:

 <LineChart
                     width={900}
                     height={400}
                     data={this.state.resDem}
                     series={<LineSeries type="grouped" tooltip={
                                                                    <TooltipArea
                                                                      tooltip={
                                                                        <ChartTooltip
                                                                          followCursor={true}
                                                                          modifiers={{
                                                                            offset: '5px, 5px'
                                                                          }}
                                                                          content={(data,color) => (
                                                                            <TooltipTemplate
                                                                              color='black'
                                                                              value={{
                                                                                x: data.x,
                                                                                y: data.y
                                                                              }}
                                                                            />
                                                                          )}
                                                                        />
                                                                      }
                                                                    />
                                                                  }
                                />

Thanks.

**Comment by steppy452** [comment]
@amcdnl I was actually just running into this same issue recently. I noticed that `TooltipTemplate` css file has the color hardcoded for the label and value:
https://github.com/jask-oss/reaviz/blob/master/src/common/Tooltip/TooltipTemplate.module.scss#L4

we could consider changing this to be something like `color: var(--color-on-background)` though we wouldn't have opacity available here unless we created another rgb equivalent variable. thoughts?

**Comment by amcdnl** [comment]
Oh - thats a mistake then - it should be using a variable!

**Comment by steppy452** [comment]
PR #124

**Comment by LeelaBasavaiah** [comment]
Thanks. I see this is merged. Can yo please show me how do I use this? What value do I give to the code TooltipTemplate color property. I want to change the tool tip text color to black.

<TooltipTemplate
color='black'
value={{
x: data.x,
y: data.y
}}
/>

**Comment by steppy452** [comment]
@LeelaBasavaiah it's based on the css variable `--color-on-background`
