### ISSUE TITLE
CalendarHeatmap throws error "TypeError date.getFullYear is not a function"

### ISSUE THREAD

**Issue by elimist3** [jask-oss/reaviz#130]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When attempting to run the CalendarHeatmap example, the following runtime error gets thrown:
`TypeError: date.getFullYear is not a function. (In 'date.getFullYear()', 'date.getFullYear' is undefined)`

## Expected behavior

CalendarHeatmap demo should work without modification

## Minimal reproduction of the problem with instructions
* Step 1: Set up a minimal react project with CalendarHeatmap
* Step 2: Use the default demo data

Minimal demo: https://codesandbox.io/s/reaviz-codesandbox-template-heg4x?file=/src/App.js

## What is the motivation / use case for changing the behavior?
n/a

## Environment

<pre><code>
Libs:
- react version: 16.13.1 (latest - Still an issue in this version)
- reaviz version: 8.1.2

Browser:
- [X] Chrome (desktop) version 80.0.3987.149
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 75.0b5
- [X] Safari (desktop) version 13.1
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by josh-williams** [comment]
Hi @elimist3. This component actually requires `Date` instances to be passed as `key`s in the data. I forked your codesandbox here and converted the keys to date and it works:

https://codesandbox.io/s/reaviz-codesandbox-template-6ew0d

**Comment by elimist3** [comment]
@josh-williams Awesome! Thanks so much for the tip.
