### ISSUE TITLE
Is there anything similar to the AnalyserNode in the Web API?

### ISSUE THREAD

**Issue by jshuadvd** [jask-oss/reaviz#131]
<pre>
<code>
## I'm submitting a...

[ X ] Question
</code></pre>

Hi there, looking to implement a real time data stream and was wondering if there is an easy way to do this with a Sonar, Line or Bar chart from the library. 

https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode

**Comment by josh-williams** [comment]
There is no built-in support for AnalyserNode in reaviz, but I think you should be able to instantiate and setup the AnalyserNode in a parent component and then call [getByteTimeDomainData](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getByteTimeDomainData) and transform that into a data array that you can pass to Reaviz. Something like this... (I haven't actually tested this code)
```
const bufferLength = analyser.fftSize;
const dataArray = new Uint8Array(bufferLength);
analyser.getByteTimeDomainData(dataArray);
let x = 0;
const reavizData = [];
for(var i = 0; i < bufferLength; i++) {
  reavizData.push({
  	key: i,
  	data: dataArray[i]
  });
}
```
I'm going to close this issue for now but feel free to comment if you have more questions.

**Comment by jshuadvd** [comment]
Hi @josh-williams Great name ;)

Okay, I will try something like this to see if it works. Thank you!

In general, is there a built in or easy way for real time visualizations? Perhaps a time series or a method to pipe real time data like cryptocurrency pricing? 

Something similar to [this](https://apexcharts.com/react-chart-demos/line-charts/realtime/),  or [this](https://nivo.rocks/storybook/?path=/story/line--real-time-chart) ?

**Comment by josh-williams** [comment]
For real time visualizations you should be able to just modify the data array passed to the chart as new data comes in. We don't have any separate APIs for real time.

**Comment by jshuadvd** [comment]
@josh-williams thank you for your quick response :) 

Could you possibly provide an example of that please? 

Given the demo [here](https://github.com/jask-oss/reaviz/blob/master/demo/sonar.ts). And rendering my chart as is in the story: 

`<SonarChart width={300} height={50} data={sonarData} />`

**Comment by jshuadvd** [comment]
Wanted to prevent stale here! :)

**Comment by josh-williams** [comment]
Hi Joshua. The chart will render whatever data you pass in. So if you want it to update in realtime, you would just update that `sonarData` array by appending to the end of the array and/or removing data from the beginning of it.

**Comment by jshuadvd** [comment]
Hi Josh! Thank you for this. I will try and let you know my results. Do you guys plan on showcasing this for the library in the near future ?
