### ISSUE TITLE
Unable to set scale of yAxis on LineChart

### ISSUE THREAD

**Issue by Rocinante89** [jask-oss/reaviz#14]
## I'm submitting a...

<pre><code>
[X ] Documentation issue or request
</code></pre>

## What is the motivation / use case for changing the behavior?
Is there a way to set the scale of the y-axis to the min/max values of the data points? It doesn't make sense to start at 0 for my use case. 

I can't see any reference to it in the docs but had a play around with the below code to no avail

    yAxis={<LinearYAxis type={'value'} scaled={true} scale={??}/>}

**Comment by amcdnl** [comment]
Can you make a demo of what your trying to accomplish? Or give me some data to play w/?

**Comment by Rocinante89** [comment]
I can't make a demo, but basically, I am trying to make a linechart where the scale of the y axis doesn't start at 0? The data I'm using is weights in kg/lbs, so will never be anywhere near 0.

It would look something like this [{
                key: new Date(01/01/2019),
                data: 120,
            },
{
                key: new Date(01/01/2019),
                data: 120,
            }]

**Comment by rvdende** [comment]
I'm trying to find documentation on this aswell. @Rocinante89 did you figure it out?

**Comment by rvdende** [comment]
Just found a solution.. kind of.

Use the below yAxis, and set domain as minimum and maximum. You'll have to loop over your data and find the min/max. 

```js
<AreaChart style={style}
            yAxis={<LinearYAxis
                type="value"
                scaled={true}
                domain={[70, 150]}
            />}
            data={data} />
```

**Comment by Rocinante89** [comment]
@rvdende I actually parked it and moved on to other work. Cheers for posting the solution though!
