### ISSUE TITLE
How do you style hover labels/popovers?

### ISSUE THREAD

**Issue by d3vhound** [jask-oss/reaviz#50]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

ON the demo site the labels look really nice and I thought those were the default but I get unstyled text instead. 
<img width="932" alt="Screen Shot 2019-05-08 at 8 04 06 AM" src="https://user-images.githubusercontent.com/17565159/57377450-1be46080-7168-11e9-8a4f-2f9495ea05c4.png">

## Expected behavior
How do you provide custom labels or use the defaults in the demo?

Edit: by label I mean popover/hover text when you move the cursor over a point

**Comment by steppy452** [comment]
You're missing this import:
https://github.com/jask-oss/reaviz/blob/master/docs/getting-started/css-vars.md

**Comment by d3vhound** [comment]
Ah makes sense. Thanks for the quick reply!
