### ISSUE TITLE
Attempted import error: 'RadialGauge' is not exported from 'reaviz'

### ISSUE THREAD

**Issue by d3vhound** [jask-oss/reaviz#51]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Trying to use RadialGauge and I don't think it's exported properly.  I'm using reaviz 2.0.0 and react 16.8.6. 

<pre><code>
import { RadialGaugeSeries, RadialGauge  } from "reaviz";
</code></pre>

This is the correct way to import RadialGauge right?

Heres a codesandbox demo
https://codesandbox.io/s/qqko20p186?fontsize=14

I assume it's just a matter of fixing the index.d.ts file.

**Comment by d3vhound** [comment]
Yeah index.d.ts does not have the RadialGauge export

`export * from "./AreaChart";
export * from "./BarChart";
export * from "./HivePlot";
export * from "./LineChart";
export * from "./Map";
export * from "./PieChart";
export * from "./Sankey";
export * from "./ScatterPlot";
export * from "./Sparkline";
export * from "./common";`

**Comment by amcdnl** [comment]
For the time being, you can import it like `import { RadialGauge } from 'reaviz/RadialGauge';`

**Comment by ZacharyLangley** [comment]
Doesn't seem to work. I'm trying to import it your way and it is still not found.
I tried: import {RadialGauge, RadialGaugeSeries} from 'reaviz/dist/RadialGauge';
and it isnt found either.

**Comment by amcdnl** [comment]
Fixed in latest 2.0.1

**Comment by ZacharyLangley** [comment]
Thanks you're the best
