### ISSUE TITLE
Map causing app crash

### ISSUE THREAD

**Issue by ynahmany** [jask-oss/reaviz#94]
## Current behavior
<pre><code>
err TypeError: __webpack_require__.e is not a function
    at Function.fn.e (bootstrap:877)
    at Map$1.componentDidMount (index.js:5443)
    at commitLifeCycles (react-dom.development.js:17334)
    at commitAllLifeCycles (react-dom.development.js:18736)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at commitRoot (react-dom.development.js:18948)
    at react-dom.development.js:20418
    at Object.unstable_runWithPriority (scheduler.development.js:255)
</code></pre>

## Expected behavior
Not to crash.

## Minimal reproduction of the problem with instructions
<code>
import { Map, MapMarker } from 'reaviz';

<Map
          height={350}
          width={500}
          markers={[
            <MapMarker coordinates={[-122.490402, 37.786453]} />,
            <MapMarker coordinates={[-58.3816, -34.6037]} />,
            <MapMarker coordinates={[-97.7437, 30.2711]} tooltip="Austin, TX" />,
          ]}
        />
</code>

### reaviz version : 5.0.0 - just upgraded. 

Can you please assist ?

**Comment by mutsumiya** [comment]
@ynahmany 
I tried to see the error with your reproduction code (thanks for providing that!) but it worked without any error except the import line. I had to add `/Map` (`from 'reaviz/Map'` instead of `from 'reaviz'`) to be able to render the map properly in an app. So could you try to see if adding `/Map` fixes your issue?

**Comment by ynahmany** [comment]
Hi @mutsumiya, 
Thanks for the quick reply!
Unfortunately, it doesn't work, the path is not recognized.
`import Map from 'reaviz/Map';`

<code>
Module not found: Error: Can't resolve 'reaviz/Map'
</code>

I tried to manually debug it using your repository, seems like the dynamic import not working as it should be. 
I am using Webpack for my react application and I think the problem is between the commonJS and ESmodules bundling.

`    componentDidMount() {
        import('world-atlas/countries-110m.json').then(geojson => {
         ...
`
 Let me know what you think.

**Comment by mutsumiya** [comment]
Hi @ynahmany,
Thanks for checking the path and debugging it! Based on your hint, I found one config related for the bundling and fixed that, which has been published as v5.0.1.

So could you try the latest version? Hopefully your issue will be gone soon 🤞

**Comment by mutsumiya** [comment]
Hi @ynahmany,
Thanks for waiting! Finally we fixed both the dist files and Map's countries json issues, which was published as v5.0.2. So could you try the version to see if you issue is resolved?

**Comment by ynahmany** [comment]
Hi @mutsumiya 
5.0.1 didn't solve it, but 5.0.2 did!
Thanks a lot for the quick fix!!

**Comment by mutsumiya** [comment]
Hi @ynahmany, glad to hear that and thanks for checking both versions!
