### ISSUE TITLE
Reaviz giving missing declaration file error after version update

### ISSUE THREAD

**Issue by Rocinante89** [jask-oss/reaviz#95]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When updating package from 2.7.1 to 5.0.1 via npm in a create react app typescript project ith throws an error

Could not find a declaration file for module 'reaviz'. '/app/node_modules/reaviz/dist/index.cjs.js' implicitly has an 'any' type.

## Environment

<pre><code>
Libs:
- react version: 16.10.1
- reaviz version: 5.0.1

</code></pre>

**Comment by mutsumiya** [comment]
Thanks for reporting this issue, @Rocinante89! We fixed the declaration file issue, which was published as v5.0.2. So could you try the version to see if you issue is resolved?

**Comment by Rocinante89** [comment]
That resolved it, @mutsumiya. Thanks!
